//
//  TapStoreTests.swift
//  BreweryTests
//

import Foundation
import Testing
@testable import Brewery

struct TapStoreTests {

    // MARK: - Tap naming

    @Test("tap directory names map to user/repo, non-taps yield nil")
    func tapNaming() {
        #expect(TapStore.tapName(user: "Charmbracelet", repoDirectory: "homebrew-tap") == "charmbracelet/tap")
        #expect(TapStore.tapName(user: "oven-sh", repoDirectory: "homebrew-bun") == "oven-sh/bun")
        #expect(TapStore.tapName(user: "someone", repoDirectory: "not-a-tap") == nil)
        // The core clones pass naming but are excluded by the scan's coreTaps check.
        #expect(TapStore.tapName(user: "homebrew", repoDirectory: "homebrew-cask") == "homebrew/cask")
        #expect(TapStore.coreTaps.contains("homebrew/cask"))
    }

    // MARK: - Definition parsing

    @Test("GoReleaser-shape formula: explicit version, class guard satisfied")
    func goReleaserFormula() throws {
        let text = """
        # typed: false
        # This file was generated by GoReleaser. DO NOT EDIT.
        class Gum < Formula
          desc "A tool for glamorous shell scripts"
          homepage "https://charm.land/"
          version "0.17.0"
          license "MIT"
          url "https://github.com/charmbracelet/gum/releases/download/v#{version}/gum_#{version}.tar.gz"
        end
        """
        let parsed = try #require(TapStore.parseFormula(text))
        #expect(parsed.desc == "A tool for glamorous shell scripts")
        #expect(parsed.homepage == "https://charm.land/")
        #expect(parsed.version == "0.17.0")
        #expect(parsed.license == "MIT")
        #expect(parsed.deprecated == false)
        #expect(parsed.disabled == false)
    }

    @Test("implicit version and compound license stay honest: absent version, first quoted license")
    func implicitVersionFormula() throws {
        let text = """
        class AvrGccAT14 < Formula
          desc "GNU compiler collection for AVR 8-bit and 32-bit Microcontrollers"
          homepage "https://www.gnu.org/software/gcc/gcc.html"
          url "https://ftp.gnu.org/gnu/gcc/gcc-14.1.0/gcc-14.1.0.tar.xz"
          license "GPL-3.0-or-later" => { with: "GCC-exception-3.1" }
          deprecate! date: "2026-01-01", because: :unsupported
        end
        """
        let parsed = try #require(TapStore.parseFormula(text))
        #expect(parsed.version == nil)
        #expect(parsed.license == "GPL-3.0-or-later")
        #expect(parsed.deprecated)
        // A url containing #{version} must never populate the version field — line anchoring.
        #expect(parsed.homepage == "https://www.gnu.org/software/gcc/gcc.html")
    }

    @Test("escaped quotes in desc survive; first stanza wins")
    func escapedQuotes() throws {
        let text = """
        class Widget < Formula
          desc "A \\"quoted\\" tool"
          desc "second desc must not win"
          homepage "https://example.com"
        end
        """
        let parsed = try #require(TapStore.parseFormula(text))
        #expect(parsed.desc == "A \"quoted\" tool")
    }

    /// `name` is a cask stanza, but brew's service DSL owns `name macos:` too
    /// (`service.rb:96`) and the scanner is indentation-blind — so mongodb/brew's
    /// `name macos: "#{plist_name}"` became the formula's title on the card, in the pane
    /// header, on its Services row and in the uninstall dialog. A formula has no display name.
    @Test("a formula's service block never becomes its display name")
    func serviceNameIsNotADisplayName() throws {
        let text = """
        class MongodbCommunity < Formula
          desc "High-performance, schema-free, document-oriented database"
          homepage "https://www.mongodb.com/"
          service do
            run [opt_bin/"mongod", "--config", etc/"mongod.conf"]
            keep_alive true
            name macos: "#{plist_name}"
            log_path var/"log/mongodb/output.log"
          end
        end
        """
        let parsed = try #require(TapStore.parseFormula(text))
        #expect(parsed.displayName == nil)
        #expect(parsed.desc == "High-performance, schema-free, document-oriented database")
    }

    @Test("stray root-level Ruby is not a formula")
    func classGuard() {
        #expect(TapStore.parseFormula("puts \"release script\"\ndesc \"not a formula\"") == nil)
        #expect(TapStore.parseFormula("class Helper\n  desc \"still not one\"\nend") == nil)
    }

    @Test("cask parsing: token guard, display name, :latest version stays absent, artifacts")
    func caskParsing() throws {
        let text = """
        cask "widget-app" do
          version :latest
          name "Widget App"
          desc "Does widget things"
          homepage "https://widget.example"
          app "Widget.app"
          app "Widget Helper.app"
          binary "Widget.app/Contents/MacOS/widgetctl"
        end
        """
        let parsed = try #require(TapStore.parseCask(text))
        #expect(parsed.displayName == "Widget App")
        #expect(parsed.desc == "Does widget things")
        #expect(parsed.version == nil)
        // Every app stanza collected; the binary's command is the path's basename.
        #expect(parsed.artifacts == [
            CaskArtifact(kind: .app, names: ["Widget.app", "Widget Helper.app"]),
            CaskArtifact(kind: .binary, names: ["widgetctl"])
        ])
        #expect(TapStore.parseCask("class NotACask < Formula\nend") == nil)
    }

    // MARK: - Graveyard rule

    @Test("versioned duplicates skipped unless installed; standalone @-names kept")
    func graveyard() {
        let files = ["bun.rb", "bun@0.1.10.rb", "bun@1.2.0.rb", "avr-gcc@9.rb"].map {
            URL(filePath: "/tap/Formula/\($0)")
        }
        // No base `avr-gcc.rb` exists, so `avr-gcc@9` is a real package, not a graveyard entry.
        let none = TapStore.graveyarded(files, kind: .formula, installed: [])
        #expect(none.map(\.lastPathComponent) == ["bun.rb", "avr-gcc@9.rb"])

        // An installed old version keeps its catalog entry.
        let installed = TapStore.graveyarded(files, kind: .formula,
                                             installed: ["formula:bun@1.2.0"])
        #expect(installed.map(\.lastPathComponent) == ["bun.rb", "bun@1.2.0.rb", "avr-gcc@9.rb"])
    }

    // MARK: - Remote normalization

    @Test("remote forms normalize to plain https; unusable forms degrade to nil")
    func remotes() {
        #expect(TapStore.normalizedRemote("https://github.com/charmbracelet/homebrew-tap")
                == "https://github.com/charmbracelet/homebrew-tap")
        #expect(TapStore.normalizedRemote("https://github.com/oven-sh/homebrew-bun.git")
                == "https://github.com/oven-sh/homebrew-bun")
        #expect(TapStore.normalizedRemote("git@github.com:supabase/homebrew-tap.git")
                == "https://github.com/supabase/homebrew-tap")
        #expect(TapStore.normalizedRemote("") == nil)
    }

    // MARK: - Directory rules (fixture tree on disk)

    @Test("first-existing dir wins and root strays are ignored; casks scanned from Casks")
    func directorySelection() throws {
        let fm = FileManager.default
        let root = fm.temporaryDirectory.appending(path: "taptest-\(UUID().uuidString)")
        defer { try? fm.removeItem(at: root) }

        // A tap with Formula/ AND a stray root .rb: the root file must be ignored.
        let formulaDir = root.appending(path: "Formula/nested")
        try fm.createDirectory(at: formulaDir, withIntermediateDirectories: true)
        let real = "class Real < Formula\n  desc \"real\"\nend"
        try real.write(to: formulaDir.appending(path: "real.rb"), atomically: true, encoding: .utf8)
        try "puts :stray".write(to: root.appending(path: "stray.rb"), atomically: true, encoding: .utf8)

        let formulae = TapStore.formulaFiles(at: root)
        #expect(formulae.map(\.lastPathComponent) == ["real.rb"])

        let caskDir = root.appending(path: "Casks")
        try fm.createDirectory(at: caskDir, withIntermediateDirectories: true)
        try "cask \"thing\" do\nend".write(to: caskDir.appending(path: "thing.rb"),
                                           atomically: true, encoding: .utf8)
        #expect(TapStore.caskFiles(at: root).map(\.lastPathComponent) == ["thing.rb"])

        // Root-layout tap (no Formula/): top-level files only.
        let flat = fm.temporaryDirectory.appending(path: "taptest-flat-\(UUID().uuidString)")
        defer { try? fm.removeItem(at: flat) }
        try fm.createDirectory(at: flat.appending(path: "scripts"), withIntermediateDirectories: true)
        try real.write(to: flat.appending(path: "rootformula.rb"), atomically: true, encoding: .utf8)
        try real.write(to: flat.appending(path: "scripts/hidden.rb"), atomically: true, encoding: .utf8)
        #expect(TapStore.formulaFiles(at: flat).map(\.lastPathComponent) == ["rootformula.rb"])
    }

    // MARK: - Trust store

    @Test("trust.json parses: keys, lowercasing, URL entries tolerated, partial trust counted")
    func trustParsing() {
        let json = """
        {"trustedtaps": ["Oven-sh/Bun", "https://git.example/foo/homebrew-bar"],
         "trustedformulae": ["charmbracelet/tap/crush", "charmbracelet/tap/freeze"],
         "trustedcasks": ["some/tap/thing"]}
        """
        let state = TapStore.TrustStore.parse(Data(json.utf8))

        #expect(state.isTrusted("oven-sh/bun"))          // lowercased on both sides
        #expect(state.isTrusted("charmbracelet/tap") == false)   // only items are trusted there
        #expect(state.trustedItemCount(in: "charmbracelet/tap") == 2)
        #expect(state.trustedItemCount(in: "some/tap") == 1)
        // A URL-shaped tap entry matches no user/repo name — conservative untrusted.
        #expect(state.isTrusted("foo/bar") == false)
    }

    @Test("consent asked exactly when installing would grant new trust")
    func trustConsent() {
        let state = TrustState(taps: ["oven-sh/bun"],
                               trustedItems: ["charmbracelet/tap/gum"])

        #expect(state.needsConsent(tap: "oven-sh/bun", name: "bun") == false)         // tap trusted
        #expect(state.needsConsent(tap: "charmbracelet/tap", name: "gum") == false)   // item trusted
        #expect(state.needsConsent(tap: "charmbracelet/tap", name: "Gum") == false)   // case folds
        #expect(state.needsConsent(tap: "charmbracelet/tap", name: "crush"))  // neither
        #expect(state.needsConsent(tap: "homebrew/core", name: "wget") == false)      // implicit trust
    }

    @Test("malformed or missing trust data reads as nothing trusted")
    func trustDefensive() {
        #expect(TapStore.TrustStore.parse(Data("not json".utf8)) == TrustState())
        #expect(TapStore.TrustStore.parse(Data("[1,2]".utf8)) == TrustState())
        #expect(TrustState().isTrusted("any/tap") == false)
        // Official taps are implicitly trusted — brew never writes them to the store.
        #expect(TrustState().isTrusted("homebrew/command-not-found"))
        #expect(TrustState().trustedItemCount(in: "any/tap") == 0)
    }

    @Test("trust store path follows brew's resolution against the child environment")
    func trustCandidates() {
        let home = URL(filePath: "/Users/u")
        func paths(_ environment: [String: String]) -> [String] {
            TapStore.TrustStore.candidates(environment: environment, home: home).map(\.path)
        }

        // XDG set → its path first; the historical probes follow, deduped.
        #expect(paths(["XDG_CONFIG_HOME": "/Users/u/.config"]) == [
            "/Users/u/.config/homebrew/trust.json",
            "/Users/u/.homebrew/trust.json",
        ])
        // brew's own fallback var, only consulted when XDG_CONFIG_HOME is absent.
        #expect(paths(["HOMEBREW_XDG_CONFIG_HOME": "/xdg"]).first == "/xdg/homebrew/trust.json")
        #expect(paths(["XDG_CONFIG_HOME": "/a", "HOMEBREW_XDG_CONFIG_HOME": "/b"]).first
                == "/a/homebrew/trust.json")
        // Neither set → ~/.homebrew first (brew's rule), ~/.config kept as a probe.
        #expect(paths([:]) == [
            "/Users/u/.homebrew/trust.json",
            "/Users/u/.config/homebrew/trust.json",
        ])
    }

    @Test("tap name validation: user/repo only — no URLs, flags or extra segments")
    func tapNameValidation() {
        #expect(AppModel.isValidTapName("oven-sh/bun"))
        #expect(AppModel.isValidTapName("Some_User/repo.name"))
        #expect(AppModel.isValidTapName("oven-sh") == false)
        #expect(AppModel.isValidTapName("a/b/c") == false)
        #expect(AppModel.isValidTapName("https://github.com/x/y") == false)
        #expect(AppModel.isValidTapName("-flag/repo") == false)   // dash-prefix is doubly rejected
        #expect(AppModel.isValidTapName("") == false)
        #expect(AppModel.isValidTapName("user/repo name") == false)
    }

    // MARK: - Effective-tap plumbing

    @Test("receipt tap normalization: core and absent fold to nil")
    func receiptTapNormalization() {
        #expect(Receipts.normalizedTap("charmbracelet/tap") == "charmbracelet/tap")
        #expect(Receipts.normalizedTap("homebrew/core") == nil)
        #expect(Receipts.normalizedTap("homebrew/cask") == nil)
        #expect(Receipts.normalizedTap(nil) == nil)
        #expect(Receipts.normalizedTap("") == nil)
    }

    @Test("tap-aware source URL: github remotes link, others and core keep their rules")
    func sourceURL() {
        let tapPackage = Package(kind: .formula, name: "gum", displayName: nil, desc: nil,
                                 homepage: nil, version: "1.0", deprecated: false, disabled: false,
                                 rubySourcePath: "gum.rb", tap: "charmbracelet/tap",
                                 tapRemote: "https://github.com/charmbracelet/homebrew-tap")
        #expect(tapPackage.rubySourceURL
                == URL(string: "https://github.com/charmbracelet/homebrew-tap/blob/HEAD/gum.rb"))

        let elsewhere = Package(kind: .formula, name: "x", displayName: nil, desc: nil,
                                homepage: nil, version: "", deprecated: false, disabled: false,
                                rubySourcePath: "x.rb", tap: "a/b",
                                tapRemote: "https://gitlab.com/a/homebrew-b")
        #expect(elsewhere.rubySourceURL == nil)

        let core = Package(kind: .formula, name: "wget", displayName: nil, desc: nil,
                           homepage: nil, version: "", deprecated: false, disabled: false,
                           rubySourcePath: "Formula/w/wget.rb")
        #expect(core.rubySourceURL
                == URL(string: "https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/w/wget.rb"))
    }

    @Test("tap labels: the real tap, or the core tap the kind implies")
    func tapLabels() {
        let tap = Package(kind: .formula, name: "gum", displayName: nil, desc: nil, homepage: nil,
                          version: "", deprecated: false, disabled: false, tap: "charmbracelet/tap")
        #expect(tap.tapLabel == "charmbracelet/tap")

        let core = Package(kind: .cask, name: "iterm2", displayName: nil, desc: nil, homepage: nil,
                           version: "", deprecated: false, disabled: false)
        #expect(core.tapLabel == "homebrew/cask")
    }

    /// The scan-membership guard, which had no test: deleting `tapScan.taps.contains(tap)`
    /// from `qualifiedName` left the whole suite green. It is load-bearing — a qualified name
    /// whose tap is not installed makes brew *clone that tap on demand*
    /// (`cmd/install.rb`), an implicit mutation the app must never cause, and a stale receipt
    /// naming a since-untapped tap is exactly how you get one. A fresh model has an empty
    /// scan, so an effective tap that is genuinely present in the receipt must still reach
    /// brew as a bare short name. The consent gate mirrors the same guard, for free.
    @MainActor
    @Test("an effective tap outside the scan is never qualified into argv")
    func unscannedTapIsNotQualified() {
        let gum = Package(kind: .formula, name: "gum", displayName: nil, desc: nil, homepage: nil,
                          version: "0.14", deprecated: false, disabled: false)
        let model = AppModel()
        model.installed[gum.id] = InstalledInfo(versions: ["0.14"], tap: "charmbracelet/tap")

        #expect(model.effectiveTap(for: gum) == "charmbracelet/tap")
        #expect(model.qualifiedName(for: gum) == "gum")
        #expect(model.installNeedsTrustConsent(gum) == false)
    }
}
